name: whorld
description: whorld ported to the web
dependencies:
  vector_math: ">=2.0.5 <3.0.0"
dev_dependencies:
  build_runner: ^0.8.8
  args: ">=0.13.0"
  build_web_compilers: ^0.4.0
  webdev: any
environment:
  sdk: ">=1.24.0 <= 2.0.0"

